    --Total five tables used in the php.
    --"Users", "Unit", "Study", "Step", "Student_step_solution"

    CREATE TABLE "SYSTEM"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"ROLE_NUM" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CAMPUS_LOCATION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("USER_ID"));

      CREATE TABLE "SYSTEM"."UNIT" 
   (	"UNIT_CODE" VARCHAR2(50 BYTE), 
	"UNIT_TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("UNIT_CODE"));

     CREATE TABLE "SYSTEM"."STUDY" 
   (	"CASE_ID" NUMBER(*,0), 
	"UNIT_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"WEEK_TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CASE_TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("CASE_ID"));

     CREATE TABLE "SYSTEM"."STEP" 
   (	"STEP_ID" NUMBER(*,0), 
	"CASE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STEP_DESCRIPTION" VARCHAR2(2000 BYTE), 
	"STEP_MARK" FLOAT(126), 
	"ANSWER" VARCHAR2(2000 BYTE), 
	 PRIMARY KEY ("STEP_ID"));

       CREATE TABLE "SYSTEM"."STUDENT_STEP_SOLUTION" 
   (	"USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STEP_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "CASE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STUDENT_ANSWER" VARCHAR2(2000 BYTE),  
	"INDIVIDUAL_STEP_MARK" FLOAT(126), 
	"SOLUTION_UPDATED_TIME" TIMESTAMP (6), 
	"SOLUTION_SUBMITTED_TIME" TIMESTAMP (6), 
	 FOREIGN KEY ("USER_ID"));